name: Build LLVM-NM Prebuilt Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag name'
        required: false
        default: 'nightly'

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: brew install cmake ninja

    - name: Configure and build llvm-nm
      run: |
        mkdir build
        cd build
        cmake -G Ninja ../llvm \
          -DLLVM_ENABLE_PROJECTS=llvm \
          -DLLVM_TOOL_LLVM_NM_BUILD=ON \
          -DLLVM_TARGETS_TO_BUILD="X86" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
        ninja llvm-nm

    - name: Prepare artifact
      run: |
        mkdir -p llvm-nm-macos-${{ matrix.arch }}
        cp build/bin/llvm-nm llvm-nm-macos-${{ matrix.arch }}/
        file llvm-nm-macos-${{ matrix.arch }}/llvm-nm
        # 可加 README

    - name: Archive
      run: |
        tar -czf llvm-nm-macos-${{ matrix.arch }}.tar.gz llvm-nm-macos-${{ matrix.arch }}/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: llvm-nm-macos-${{ matrix.arch }}
        path: llvm-nm-macos-${{ matrix.arch }}.tar.gz

  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: choco install cmake ninja

    - name: Configure and build llvm-nm
      run: |
        mkdir build
        cd build
        cmake -G Ninja ../llvm ^
          -DLLVM_ENABLE_PROJECTS=llvm ^
          -DLLVM_TOOL_LLVM_NM_BUILD=ON ^
          -DLLVM_TARGETS_TO_BUILD="X86" ^
          -DCMAKE_BUILD_TYPE=Release
        ninja llvm-nm

    - name: Prepare artifact
      run: |
        mkdir llvm-nm-windows-${{ matrix.arch }}
        copy build\bin\llvm-nm.exe llvm-nm-windows-${{ matrix.arch }}\
        # 可加 README

    - name: Archive
      run: |
        Compress-Archive -Path llvm-nm-windows-${{ matrix.arch }}\* -DestinationPath llvm-nm-windows-${{ matrix.arch }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: llvm-nm-windows-${{ matrix.arch }}
        path: llvm-nm-windows-${{ matrix.arch }}.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build build-essential

    - name: Configure and build llvm-nm
      run: |
        mkdir build
        cd build
        cmake -G Ninja ../llvm \
          -DLLVM_ENABLE_PROJECTS=llvm \
          -DLLVM_TOOL_LLVM_NM_BUILD=ON \
          -DLLVM_TARGETS_TO_BUILD="X86" \
          -DCMAKE_BUILD_TYPE=Release
        ninja llvm-nm

    - name: Prepare artifact
      run: |
        mkdir -p llvm-nm-linux-x86_64
        cp build/bin/llvm-nm llvm-nm-linux-x86_64/
        file llvm-nm-linux-x86_64/llvm-nm
        # 可加 README

    - name: Archive
      run: |
        tar -czf llvm-nm-linux-x86_64.tar.gz llvm-nm-linux-x86_64/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: llvm-nm-linux-x86_64
        path: llvm-nm-linux-x86_64.tar.gz

  create-release:
    needs: [build-macos, build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release assets
      run: |
        mkdir release-assets
        find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec cp {} release-assets/ \;
        ls -la release-assets/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release_tag || github.ref_name }}
        name: LLVM-NM Prebuilt Binaries ${{ github.event.inputs.release_tag || github.ref_name }}
        body: >-
          ## LLVM-NM Prebuilt Binaries (Release Build)

          This release contains prebuilt llvm-nm binaries for macOS, Windows, and Linux.

          ### macOS
          - `llvm-nm-macos-x86_64.tar.gz`
          - `llvm-nm-macos-arm64.tar.gz`

          ### Windows
          - `llvm-nm-windows-x64.zip`
          - `llvm-nm-windows-x86.zip`

          ### Linux
          - `llvm-nm-linux-x86_64.tar.gz`

          Each package includes:
          - **llvm-nm**: LLVM's symbol table dumper tool.
          - README with usage instructions.

          Built from commit: ${{ github.sha }}
        files: release-assets/*
        draft: false
        prerelease: ${{ github.event.inputs.release_tag == 'nightly' || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
